# Generated by Django 6.0.3 on 2026-07-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="in_use",
            field=models.BooleanField(
                default=False, help_text="Child is currently using this approved app"
            ),
        ),
    ]
