# Generated by Django 5.2.2 on 2026-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0002_accessrequest_in_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="focussession",
            name="break_seconds",
            field=models.IntegerField(
                default=0, help_text="Total break time in seconds"
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="focus_score",
            field=models.FloatField(
                default=0.0, help_text="Calculated focus percentage"
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="session_type",
            field=models.CharField(
                choices=[("FOCUS", "Focus"), ("STUDY", "Study")],
                default="FOCUS",
                help_text="FOCUS = Pomodoro with app blocking, STUDY = free-form timer",
                max_length=10,
            ),
        ),
    ]
