# Generated by Django 6.0.3 on 2026-08-16 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0003_focussession_break_seconds_focussession_focus_score_and_more"),
        ("tasks", "0003_alter_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="focussession",
            name="blocked_attempts",
            field=models.IntegerField(
                default=0,
                help_text="Number of blocked access attempts during this session",
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="early_exit",
            field=models.BooleanField(
                default=False,
                help_text="Child ended the session before the planned duration",
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="task",
            field=models.ForeignKey(
                blank=True,
                help_text="To-Do task the child is working on during this session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="focus_sessions",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="focussession",
            name="planned_duration",
            field=models.IntegerField(
                help_text="Planned duration in minutes (25, 50, 90, or custom)"
            ),
        ),
    ]
