# Generated by Django 6.0.3 on 2026-08-17 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0004_focussession_blocked_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="focussession",
            name="lock_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Super Power Saving Mode - OS/browser level lock is enforced",
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="lock_violations",
            field=models.IntegerField(
                default=0,
                help_text="Number of lock violations (tab switch / minimize / leave attempt)",
            ),
        ),
        migrations.CreateModel(
            name="FocusDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("EXTENSION", "Browser Extension"),
                            ("AGENT", "Desktop Agent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, help_text="Last heartbeat received", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FocusLockEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOCK_ACTIVATED", "Lock Activated"),
                            ("LOCK_DEACTIVATED", "Lock Deactivated"),
                            ("TAB_SWITCH", "Tab Switch"),
                            ("TAB_HIDE", "Tab Hidden"),
                            ("MINIMIZE", "Window Minimized"),
                            ("WINDOW_CLOSE", "Window Closed"),
                            ("LEAVE_ATTEMPT", "Leave Attempt"),
                            ("APP_BLOCKED", "App Blocked"),
                            ("WEBSITE_BLOCKED", "Website Blocked"),
                            ("ACCESS_REQUESTED", "Access Requested"),
                            ("ACCESS_APPROVED", "Access Approved"),
                            ("ACCESS_DENIED", "Access Denied"),
                            ("DEVICE_ONLINE", "Device Online"),
                            ("DEVICE_OFFLINE", "Device Offline"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human readable description, e.g. blocked app or website name",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "notified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the linked parent(s) were notified",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_lock_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lock_events",
                        to="focus.focusdevice",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock_events",
                        to="focus.focussession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
