# Generated by Django 6.0.3 on 2026-08-23 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0005_focussession_lock_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="usage_seconds",
            field=models.IntegerField(
                default=0,
                help_text="Total seconds the child actually used the approved app",
            ),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="usage_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the child opened the approved app (focus timer freezes)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="last_tick_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last presence tick received from the child's focus page (server-side timing)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="pause_seconds_total",
            field=models.IntegerField(
                default=0,
                help_text="Total seconds the session was paused for approved app usage",
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="paused_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set while an approved app is being used - focus timer is frozen",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="focuslockevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOCK_ACTIVATED", "Lock Activated"),
                    ("LOCK_DEACTIVATED", "Lock Deactivated"),
                    ("TAB_SWITCH", "Tab Switch"),
                    ("TAB_HIDE", "Tab Hidden"),
                    ("MINIMIZE", "Window Minimized"),
                    ("WINDOW_CLOSE", "Window Closed"),
                    ("LEAVE_ATTEMPT", "Leave Attempt"),
                    ("APP_BLOCKED", "App Blocked"),
                    ("WEBSITE_BLOCKED", "Website Blocked"),
                    ("ACCESS_REQUESTED", "Access Requested"),
                    ("ACCESS_APPROVED", "Access Approved"),
                    ("ACCESS_DENIED", "Access Denied"),
                    ("APPROVED_APP_START", "Approved App Started"),
                    ("APPROVED_APP_END", "Approved App Ended"),
                    ("ACCESS_EXPIRED", "Approved Access Expired"),
                    ("APP_LAUNCHED", "App Launched Via Sadhana"),
                    ("DEVICE_ONLINE", "Device Online"),
                    ("DEVICE_OFFLINE", "Device Offline"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="FocusDeviceCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[("LAUNCH_APP", "Launch App")],
                        default="LAUNCH_APP",
                        max_length=20,
                    ),
                ),
                ("app_name", models.CharField(max_length=100)),
                ("category", models.CharField(default="APP", max_length=10)),
                (
                    "url_pattern",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Agent result / failure reason",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_commands",
                        to="focus.focussession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
