# Generated by Django 5.2.2 on 2026-09-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0006_accessrequest_usage_seconds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="focuslockevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOCK_ACTIVATED", "Lock Activated"),
                    ("LOCK_DEACTIVATED", "Lock Deactivated"),
                    ("TAB_SWITCH", "Tab Switch"),
                    ("TAB_HIDE", "Tab Hidden"),
                    ("MINIMIZE", "Window Minimized"),
                    ("WINDOW_CLOSE", "Window Closed"),
                    ("LEAVE_ATTEMPT", "Leave Attempt"),
                    ("APP_BLOCKED", "App Blocked"),
                    ("WEBSITE_BLOCKED", "Website Blocked"),
                    ("ACCESS_REQUESTED", "Access Requested"),
                    ("ACCESS_APPROVED", "Access Approved"),
                    ("ACCESS_DENIED", "Access Denied"),
                    ("APPROVED_APP_START", "Approved App Started"),
                    ("APPROVED_APP_END", "Approved App Ended"),
                    ("ACCESS_EXPIRED", "Approved Access Expired"),
                    ("APP_LAUNCHED", "App Launched Via Sadhana"),
                    ("DEVICE_ONLINE", "Device Online"),
                    ("DEVICE_OFFLINE", "Device Offline"),
                    ("UNAUTHORIZED_ACTIVITY", "Unauthorized Activity"),
                ],
                max_length=30,
            ),
        ),
    ]
