# Generated by Django 5.2.2 on 2026-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0007_alter_focuslockevent_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="focussession",
            name="break_duration",
            field=models.IntegerField(
                default=0, help_text="Duration of the current/last break in seconds"
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="break_end_time",
            field=models.DateTimeField(
                blank=True, help_text="When the break is scheduled to end", null=True
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="break_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When the break started", null=True
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="breaks_taken",
            field=models.IntegerField(
                default=0, help_text="Number of breaks taken during this session"
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="total_break_seconds",
            field=models.IntegerField(
                default=0, help_text="Total break time across all breaks in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="focussession",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("BREAK", "Break"),
                    ("COMPLETED", "Completed"),
                    ("INTERRUPTED", "Interrupted"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
