# Generated by Django 5.2.2 on 2026-09-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("focus", "0008_add_break_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="focussession",
            name="resume_seconds",
            field=models.IntegerField(
                default=0,
                help_text="Total focused time accumulated during resume periods",
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="resuming_since",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current resume period started (null if not resuming)",
                null=True,
            ),
        ),
    ]
