# Generated by Django 6.0.3 on 2026-04-01 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_goal",
                    models.IntegerField(
                        default=120, help_text="Daily study goal in minutes"
                    ),
                ),
                (
                    "weekly_goal",
                    models.IntegerField(
                        default=600, help_text="Weekly study goal in minutes"
                    ),
                ),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_goal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="Total session time in minutes"
                    ),
                ),
                (
                    "break_time",
                    models.IntegerField(
                        default=0, help_text="Total break time taken in minutes"
                    ),
                ),
                (
                    "distraction_time",
                    models.IntegerField(
                        default=0, help_text="Total distracted time in seconds"
                    ),
                ),
                ("focus_score", models.FloatField(default=0.0)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
