# Generated by Django 5.2.2 on 2026-07-14 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Emoji or icon character", max_length=10
                    ),
                ),
                ("xp_reward", models.IntegerField(default=0)),
                ("coin_reward", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RewardProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xp", models.IntegerField(default=0)),
                ("coins", models.IntegerField(default=0)),
                ("total_tasks_completed", models.IntegerField(default=0)),
                ("total_focus_sessions", models.IntegerField(default=0)),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0,
                        help_text="Consecutive days with at least one study session",
                    ),
                ),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_active_date", models.DateField(blank=True, null=True)),
                (
                    "all_tasks_done_streak",
                    models.IntegerField(
                        default=0, help_text="Consecutive days all tasks completed"
                    ),
                ),
                ("best_all_tasks_done_streak", models.IntegerField(default=0)),
                ("weekly_goals_met", models.IntegerField(default=0)),
                ("monthly_goals_met", models.IntegerField(default=0)),
                ("tasks_completed_before_8am", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-xp"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("EARN", "Earned"), ("SPEND", "Spent")],
                        default="EARN",
                        max_length=10,
                    ),
                ),
                ("xp_amount", models.IntegerField(default=0)),
                ("coin_amount", models.IntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("TASK_COMPLETE", "Task Completed"),
                            ("ALL_TASKS_DONE", "All Daily Tasks Done"),
                            ("FOCUS_SESSION", "Focus Session Completed"),
                            ("STUDY_STREAK", "Study Streak"),
                            ("WEEKLY_GOAL", "Weekly Goal Achieved"),
                            ("MONTHLY_GOAL", "Monthly Goal Achieved"),
                            ("BADGE_REWARD", "Badge Earned"),
                            ("LEVEL_UP", "Level Up"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BadgeAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("is_new", models.BooleanField(default=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="rewards.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_at"],
                "unique_together": {("user", "badge")},
            },
        ),
    ]
