# Generated by Django 5.2.2 on 2026-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="subject",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MATH", "Mathematics"),
                    ("SCIENCE", "Science"),
                    ("PROGRAMMING", "Programming"),
                    ("ENGLISH", "English"),
                    ("HISTORY", "History"),
                    ("PHYSICS", "Physics"),
                    ("CHEMISTRY", "Chemistry"),
                    ("BIOLOGY", "Biology"),
                    ("OTHER", "Other"),
                ],
                help_text="Academic subject category",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
