# Generated by Django 5.2.2 on 2026-07-15 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyDNAProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "best_study_time_label",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "favorite_subject",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "weakest_subject",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("average_focus_duration_minutes", models.FloatField(default=0.0)),
                (
                    "most_productive_day",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "least_productive_day",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "common_distraction_time",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("productivity_score", models.FloatField(default=0.0)),
                ("consistency_score", models.FloatField(default=0.0)),
                ("consistency_improvement", models.FloatField(default=0.0)),
                ("study_streak_days", models.IntegerField(default=0)),
                ("longest_streak_days", models.IntegerField(default=0)),
                ("weekly_focus_data", models.TextField(default="[]")),
                ("weekly_task_data", models.TextField(default="[]")),
                ("monthly_focus_trend", models.TextField(default="[]")),
                ("monthly_task_trend", models.TextField(default="[]")),
                ("recommendations", models.TextField(default="[]")),
                ("subject_data_json", models.TextField(default="{}")),
                ("last_analyzed", models.DateTimeField(auto_now=True)),
                ("data_points", models.IntegerField(default=0)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studydna_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Study DNA Profile",
                "verbose_name_plural": "Study DNA Profiles",
            },
        ),
    ]
