# Generated by Django 5.2.2 on 2026-07-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studydna", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studydnaprofile",
            name="goal_progress_json",
            field=models.TextField(default="{}"),
        ),
        migrations.AddField(
            model_name="studydnaprofile",
            name="missed_deadlines_json",
            field=models.TextField(default="{}"),
        ),
        migrations.AddField(
            model_name="studydnaprofile",
            name="parent_tasks_json",
            field=models.TextField(default="{}"),
        ),
        migrations.AddField(
            model_name="studydnaprofile",
            name="reward_insights_json",
            field=models.TextField(default="{}"),
        ),
    ]
