# Generated by Django 6.0.3 on 2026-08-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studydna", "0002_studydnaprofile_goal_progress_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studydnaprofile",
            name="focus_stats_json",
            field=models.TextField(default="{}"),
        ),
    ]
