# Generated by Django 6.0.3 on 2026-07-11 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=150)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("TASK_ASSIGNED", "Task Assigned"),
                            ("TASK_EDITED", "Task Edited"),
                            ("DEADLINE_CHANGED", "Deadline Changed"),
                            ("APPRECIATION", "Appreciation"),
                            ("TASK_COMPLETED", "Task Completed"),
                            ("ALL_TASKS_DONE", "All Tasks Done"),
                            ("DEADLINE_MISSED", "Deadline Missed"),
                            ("LOW_COMPLETION", "Low Completion"),
                            ("STUDY_STREAK", "Study Streak"),
                            ("DISTRACTION_ALERT", "Distraction Alert"),
                            ("TASK_REOPENED", "Task Reopened"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
