# Generated by Django 5.2.2 on 2026-09-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("IMPORTANT", "Important"),
                    ("ATTENTION_REQUIRED", "Attention Required"),
                ],
                db_index=True,
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("TASK_ASSIGNED", "Task Assigned"),
                    ("TASK_EDITED", "Task Edited"),
                    ("DEADLINE_CHANGED", "Deadline Changed"),
                    ("APPRECIATION", "Appreciation"),
                    ("TASK_COMPLETED", "Task Completed"),
                    ("ALL_TASKS_DONE", "All Tasks Done"),
                    ("DEADLINE_MISSED", "Deadline Missed"),
                    ("LOW_COMPLETION", "Low Completion"),
                    ("STUDY_STREAK", "Study Streak"),
                    ("DISTRACTION_ALERT", "Distraction Alert"),
                    ("TASK_REOPENED", "Task Reopened"),
                    ("ACCESS_REQUESTED", "Access Requested"),
                    ("ACCESS_APPROVED", "Access Approved"),
                    ("ACCESS_REJECTED", "Access Rejected"),
                    ("LOCK_VIOLATION", "Lock Violation"),
                    ("LOCK_ACTIVATED", "Lock Activated"),
                    ("LOCK_DEACTIVATED", "Lock Deactivated"),
                    ("DEVICE_OFFLINE", "Device Offline"),
                    ("FOCUS_COMPLETED", "Focus Session Completed"),
                    ("FOCUS_INTERRUPTED", "Focus Session Interrupted"),
                    ("LEVEL_UP", "Level Up"),
                    ("BADGE_EARNED", "Badge Earned"),
                    ("CHAT_MESSAGE", "Chat Message"),
                ],
                max_length=50,
            ),
        ),
    ]
