# Generated by Django 5.2.2 on 2026-09-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_notification_action_label_notification_action_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
